---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      bgp: "65001"
  bgpInstances:
  - name: "64999"
    localASN: 64999
    peers:
    - name: "64998"
      peerASN: 64998
      peerAddress: 127.0.0.1 # peer with bgp daemon on the node via localhost
      peerConfigRef:
        name: "cilium-peer" # CiliumBGPPeerConfig
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  families:
  - afi: ipv4
    safi: unicast
    advertisements:
      matchLabels:
        advertise: lbip-podcidr
---
# LoadBalancerIP & PodCIDR advertisements
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: lbip-podcidr-advertisements
  labels:
    advertise: lbip-podcidr
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
         - {key: somekey, operator: NotIn, values: ['never-used-value']} # all LoadBalancerIPs
      attributes:
        communities:
          standard: [ "65001:65002" ]
    - advertisementType: "PodCIDR"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
spec:
  blocks:
    - cidr: "10.0.10.0/24"
