---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      bgp: "65001"
  bgpInstances:
  - name: "65002"
    localASN: 65002
    peers:
    - name: "65001"
      peerASN: 65001
      peerAddress: 127.0.0.1 # peer with bgp daemon on the node via localhost
      peerConfigRef:
        name: "cilium-peer" # CiliumBGPPeerConfig
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  families:
  - afi: ipv4
    safi: unicast
    advertisements:
      matchLabels:
        advertise: lbip-podcidr
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: lbip-podcidr-advertisements
  labels:
    advertise: lbip-podcidr
spec:
  advertisements:
    - advertisementType: "PodCIDR"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
spec:
  blocks:
    - cidr: "10.0.10.0/24"
