apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
    - peer-address: 10.0.0.1 # router0 address
      peer-asn: 65000 # router0 asn
      my-asn: 65001
      node-selectors:
      - match-labels:
          bgp: "65001" # node label added from kind config
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.0.10.0/24
