debug:
  enabled: true

routingMode: tunnel
tunnelProtocol: geneve

bgpControlPlane:
  enabled: true
  v2Enabled: true
# bgp:
#   announce:
#     loadbalancerIP: true
#   enabled: true

ipam:
  mode: kubernetes

k8s:
  requireIPv4PodCIDR: true

operator:
  enabled: true
  replicas: 1
